image: Visual Studio 2015

#init:
#  - ps: if ($env:APPVEYOR_BUILD_WORKER_IMAGE -eq "Visual Studio 2015") {write-host "Uninstalling 4014507..."; cmd /c wusa /uninstall /kb:4014507 /quiet /forcerestart}
install:
- ps: $blockRdp = $true; iex ((new-object net.webclient).DownloadString('https://raw.githubusercontent.com/appveyor/ci/master/scripts/enable-rdp.ps1'))

build: off

test_script:
- ps: $start = Get-Date
- ps: $ErrorActionPreference = "Stop"
- ps: for ($i = 1; $i -le 3; $i++) {.\runtests.ps1}
- ps: $duration = (Get-Date) - $start
- ps: if($duration.TotalSeconds -gt 90) { throw "Test execution was too slow!" }
