image: Visual Studio 2015

#init:
#  - ps: if ($env:APPVEYOR_BUILD_WORKER_IMAGE -eq "Visual Studio 2015") {write-host "Uninstalling 4014507..."; cmd /c wusa /uninstall /kb:4014507 /quiet /forcerestart}
  
build_script:
- ps: for($i=1; $i -le 3; $i++) {.\runtests.ps1}