init:
- appveyor version
- ps: systeminfo

build: off

test_script:
- ps: $start = Get-Date
- ps: $ErrorActionPreference = "Stop"
- ps: for ($i = 1; $i -le 3; $i++) {.\runtests.ps1}
- ps: $duration = (Get-Date) - $start
- ps: if($duration.TotalSeconds -gt 90) { throw "Test execution was too slow!" }
